# Generated by Django 4.0.1 on 2022-02-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='CareerPath',
            new_name='career_path',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='DateOfBirth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='ProfilePic',
            new_name='profile_pic',
        ),
    ]
