# Generated by Django 4.0.2 on 2022-02-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazefah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='Gender',
            field=models.CharField(choices=[('M', 'F')], max_length=3),
        ),
    ]
