# Generated by Django 4.0.1 on 2022-02-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('company_pic', models.ImageField(default='company_pics/company.svg', upload_to='company_pics')),
                ('description', models.TextField(max_length=200)),
                ('company_website', models.URLField()),
            ],
        ),
    ]
