# Generated by Django 4.0.2 on 2022-02-10 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appliedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.job'),
        ),
    ]
