# Generated by Django 4.0.2 on 2022-02-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazefah', '0002_alter_userinformation_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Female')], max_length=10),
        ),
    ]
