# Generated by Django 4.0.2 on 2022-02-14 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_rename_profilepick_userinformation_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_applied', to='main.userinformation'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
