# Generated by Django 4.0.1 on 2022-02-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_appliedjob_job_alter_appliedjob_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='Male', max_length=10),
        ),
    ]
