# Generated by Django 4.0.1 on 2022-02-23 13:01

import builtins
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_experience_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': (builtins.id,)},
        ),
    ]
