# Generated by Django 4.0.1 on 2022-02-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userinformation_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='ProfilePic',
            field=models.ImageField(default='default.png', upload_to='media/profile_pics'),
        ),
    ]
