# Generated by Django 4.0.1 on 2022-02-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userinformation_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=10, null=True),
        ),
    ]
