# Generated by Django 4.0.2 on 2022-02-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appliedjobs_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppliedJobs',
            new_name='AppliedJob',
        ),
    ]
