# Generated by Django 4.0.2 on 2022-02-21 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_appliedjob_user_alter_userinformation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.job'),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userinformation'),
        ),
    ]
