# Generated by Django 4.0.1 on 2022-02-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userinformation_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='ProfilePic',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
