# Generated by Django 4.0.1 on 2022-02-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userinformation_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='Bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='CareerPath',
            field=models.CharField(default=-2020, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_jobs', to='main.job'),
        ),
    ]
