# Generated by Django 4.0.1 on 2022-02-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userinformation_bio_userinformation_careerpath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='Bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
