# Generated by Django 4.0.1 on 2022-02-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_userinformation_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='CareerPath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
