# Generated by Django 4.0.1 on 2022-02-15 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_userinformation_careerpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='DateOfBirth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='Experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='Gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=10, null=True),
        ),
    ]
