# Generated by Django 4.0.2 on 2022-02-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wazefah', '0004_alter_userinformation_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='Experiance',
            new_name='Experience',
        ),
    ]
