# Generated by Django 4.0.2 on 2022-02-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazefah', '0005_rename_experiance_userinformation_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.TextField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
