# Generated by Django 4.0.2 on 2022-02-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wazefah', '0006_job'),
        ('wazefah', '0006_rename_profilepick_userinformation_profilepic'),
    ]

    operations = [
    ]
